#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/
#                                    /_/           drxspace@gmail.com
#
#

# Check if it's already mounted
if [[ $EUID -ne 0 ]] ; then
	SharesDIR=$(mount -l -t vboxsf | grep -m1 $(id -u `whoami`) | cut -d ' ' -f3)
else
	SharesDIR=$(mount -l -t vboxsf | cut -d ' ' -f3 | head -1)
fi
[[ -d $SharesDIR ]] && { xdg-open $SharesDIR; exit 0; }

# Choose which one of the VBox shares to remount
SharesList=($(mount -l -t vboxsf | awk 'BEGIN { alist = ""; sep = " " } { if (alist != 'none') alist = alist $1 sep }; END { print alist }'))
if [[ ! -z ${SharesList[*]} ]]; then
	Items=""
	for AItem in ${SharesList[*]}; do
		Items="$Items FALSE $AItem"
	done
	AShare=$(zenity --list --radiolist --text="Which one share should I remount?" --column="Pick" --column="Shares" $(echo $Items))
else
	AShare=$(zenity --entry --text="I couldn't find any mounted VBox shared folder.\nIf you'd like you can type a VBox shared folder's name here:" --entry-text="vbshares")
fi
[[ -z $AShare ]] && { notify-send "Remount" "Ok! Bye." -i face-smile; exit 1; }

# Choose a folder to mount the VBox shared folder
SharesDIR=$(zenity --file-selection --directory --title="Select a folder to mount the VBox shared folder")
[[ -z $SharesDIR ]] && { notify-send "Remount" "Ok! Bye." -i face-smile; exit 2; }
SharesDIR=""$SharesDIR"/"$AShare""
mkdir -p "$SharesDIR"

# Check to see if script was invoked from terminal or not
if [ -t 0 ]; then
	RMcmd="$(which sudo) sh -c 'umount -t vboxsf $AShare ; mount -t vboxsf -o uid=$(id -u `whoami`),gid=$(id -g `whoami`) $AShare \"$SharesDIR\"'"
else	
	RMcmd="$(which gksudo) -k -D \"VBox shared folder remounter for use by $(whoami)\" \"sh -c 'umount -t vboxsf $AShare ; mount -t vboxsf -o uid=$(id -u `whoami`),gid=$(id -g `whoami`) $AShare \"$SharesDIR\"'\""
fi

# Run the command to remount the shared folder with user rights
bash -c "$RMcmd" || { notify-send "Remount" "I cound not remount the shared folder" -i face-embarrassed; exit 3; }

xdg-open $SharesDIR
notify-send "Remount" "Remounting the shared folder <b>$AShare</b> to folder <b>$SharesDIR</b> was done ok!" -i face-wink

exit 0
